"use client";
import {useEffect,useMemo,useState} from "react";
import type {CfbGame} from "@/lib/cfb/types";
import type {CfbPropsBoard} from "@/lib/cfb/props-types";
import history from "@/lib/nfl/first-sunday-six-history.json";
import snapshot from "@/lib/nfl/first-sunday-six-prices.json";
import {parseSixPrices,sixKey,sixRace,sixScenario,type SixPrice} from "@/lib/nfl/first-sunday-six";
import {PlayerMark} from "@/components/cfb/TeamMark";
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
export function FirstSundaySix({date,games,board,now}:{date:string;games:readonly CfbGame[];board:CfbPropsBoard|undefined;now:number}){
 const [custom,setCustom]=useState<{date:string;rows:SixPrice[];at:string}|null>(null);
 const [draft,setDraft]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('prob'),[limit,setLimit]=useState(12);
 const [selected,setSelected]=useState(''),[winners,setWinners]=useState('100'),[conversion,setConversion]=useState('50'),[pool,setPool]=useState('500000');
 useEffect(()=>{setCustom(null);setSelected('');setLimit(12);try{const s=JSON.parse(localStorage.getItem(`pl:first-six:${date}`)??'null');if(s?.date===date&&Array.isArray(s.rows)){const p=parseSixPrices(s.rows.map((r:SixPrice)=>`${r.player}|${r.odds}`).join('\n'));if(!p.errors.length)setCustom({date,rows:p.rows,at:String(s.at)});}}catch{}},[date]);
 const own=custom?.date===date?custom:null;
 const prices=own?.rows??(date===snapshot.date?snapshot.rows:[]);
 const race=useMemo(()=>sixRace(games,board,date,prices,now),[games,board,date,prices,now]);
 const sorted=[...race.results].filter(r=>r.player.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='value'?(b.ev??-Infinity)-(a.ev??-Infinity):(b.p??-1)-(a.p??-1));
 const focus=race.results.find(r=>sixKey(r.player)===selected)??sorted.find(r=>r.p!=null);
 const past=history.playerHistory.find(r=>sixKey(r.player)===sixKey(focus?.player??''));
 const scenario=focus?.p!=null?sixScenario(focus.p,focus.odds,Number(winners),Number(conversion)/100,Number(pool)):null;
 const importPrices=()=>{const p=parseSixPrices(draft);if(p.errors.length||!p.rows.length){setError(p.errors.slice(0,3).join(' · ')||'Enter at least one player and price.');return;}const value={date,rows:p.rows,at:new Date().toISOString()};setCustom(value);setError('');setLimit(12);try{localStorage.setItem(`pl:first-six:${date}`,JSON.stringify(value));}catch{setError('Loaded for this session; device storage unavailable.');}};
 return <section className="rounded-xl border border-gold/40 bg-surface px-3 py-2 space-y-2" aria-label="First Sunday Six">
  <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-bold text-gold">First Sunday Six <span className="text-[10px] text-muted">Caesars exclusive</span></h2><span className="text-[10px] font-bold text-muted">Experimental · {date} · {race.early.length} early games</span></div>
  <p className="text-[11px] font-semibold">Earliest touchdown by elapsed game clock across the Sunday 10 a.m. PT / 1 p.m. ET slate. One $10 single + weekly token, per your supplied promotion details. Not a parlay.</p>
  <p className="text-[10px] text-muted">{own?`Manual prices entered ${own.at}`:date===snapshot.date?snapshot.source:'No promotion prices loaded for this date.'} Generate Board refreshes the underlying First TD estimates, not these Caesars promotion prices. Global sportsbook selection does not change this Caesars-only market.</p>
  <div className="flex flex-wrap gap-2 text-[11px]"><input aria-label="Search First Sunday Six" placeholder="Search player / defense" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12);}} className="min-w-0 flex-1 rounded border border-white/20 bg-surface-2 px-2 py-1"/><select aria-label="First Sunday Six sort" value={sort} onChange={e=>setSort(e.target.value)} className="rounded border border-white/20 bg-surface-2 px-2 py-1"><option value="prob">Highest estimated win chance</option><option value="value">Best cash-ticket EV / grade</option></select></div>
  {race.closed&&<p className="text-[11px] text-gold">Early slate has started. Pregame estimates and grades are closed; live game-clock outcomes are not being modeled here.</p>}
  <div className="max-h-[460px] overflow-auto"><table className="w-full text-[11px]"><thead className="sticky top-0 bg-surface text-muted"><tr><th className="text-left">Player / game</th><th>Caesars</th><th>Est. race %</th><th>Cash grade</th><th>EV %</th></tr></thead><tbody>
   {sorted.slice(0,limit).map(r=><tr key={sixKey(r.player)} className="border-b border-white/20"><td className="py-1"><button onClick={()=>setSelected(sixKey(r.player))} className="flex items-center gap-2 text-left font-bold" aria-pressed={focus?.player===r.player}><PlayerMark league="nfl" player={r.player} headshot={r.row?.headshot} team={r.game?[r.game.home,r.game.away].find(t=>t.id===r.row?.teamId):null} teamIds={r.game?[r.game.home.id,r.game.away.id]:[]} size="sm"/><span>{r.player}<span className="block text-[9px] text-muted">{r.game?`${r.game.away.abbr} @ ${r.game.home.abbr} · 10 a.m. PT`:r.reason??'Unmatched'}{r.p==null&&r.game?` · ${r.reason}`:''}</span></span></button></td><td className="text-center font-bold">{r.odds>0?'+':''}{r.odds}</td><td className="text-center font-bold" title={r.reason??'Experimental model estimate, not a verified true probability'}>{r.p==null?'—':(100*r.p).toFixed(2)}</td><td className="text-center font-bold">{r.grade??'—'}</td><td className="text-center">{r.ev==null?'—':(100*r.ev).toFixed(1)}</td></tr>)}
  </tbody></table></div>
  {!sorted.length&&<p className="text-[11px] text-muted">No matching entries. Load prices below; unsupported or missing player estimates remain ungraded.</p>}
  {sorted.length>limit&&<button className="text-[11px] font-bold text-gold" onClick={()=>setLimit(n=>n+30)}>Show more ({sorted.length-limit})</button>}
  <details className="text-[11px] border-t border-white/10 pt-1"><summary className="cursor-pointer font-bold">Bonus-pool scenario · {focus?.player??'select an estimated player'}</summary>
   <p className="py-1 text-muted">Scenario only. The winner count is an assumption for this player, not measured popularity. Bonus bets are not cash; conversion is your assumed cash-equivalent fraction. No promo-inclusive grade or Kelly stake is asserted.</p>
   <div className="flex flex-wrap gap-2">{[['Total winning entries (including yours)',winners,setWinners],['Bonus conversion %',conversion,setConversion],['Bonus pool $',pool,setPool]].map(([label,value,setter])=><label key={String(label)} className="flex-1 min-w-32 font-bold">{String(label)}<input aria-label={String(label)} type="number" value={String(value)} onChange={e=>(setter as (s:string)=>void)(e.target.value)} className="block w-full rounded border border-white/20 bg-surface-2 px-2 py-1"/></label>)}</div>
   {scenario?<p className="py-2 font-bold">On a win: {money(scenario.bonusFace)} face-value bonus share. Estimated $10 cash-ticket EV: {money(scenario.cashEv)}. Scenario bonus cash-equivalent EV: {money(scenario.bonusEv)}. Combined scenario EV: {money(scenario.totalEv)}.</p>:<p className="py-1">Requires a current estimate, at least one whole winning entry, conversion 0–100%, and a nonnegative pool.</p>}
  </details>
  <details className="text-[11px] border-t border-white/10 pt-1"><summary className="cursor-pointer font-bold">Update Caesars promotion prices</summary><p className="py-1 text-muted">Paste one Player | +2200 per line. Replaces this date’s list on this device. Partial lists are fine; omitted players’ chances are not redistributed.</p><textarea aria-label="Caesars promotion prices" value={draft} onChange={e=>setDraft(e.target.value)} rows={4} className="w-full rounded border border-white/20 bg-surface-2 p-2"/><button onClick={importPrices} className="font-bold text-gold">Apply prices</button>{error&&<p role="alert">{error}</p>}</details>
  <details className="text-[11px] border-t border-white/10 pt-1"><summary className="cursor-pointer font-bold">Historical evidence · {history.games.toLocaleString()} games · 2016–2026</summary>
   <p className="py-1">{history.firstTDs.toLocaleString()} first TD scorers across {history.games.toLocaleString()} completed games; {history.earlySlates} Sunday early slates, {history.tiedSlates} tied slate. Through {history.latestCompletedDate}; Week 2 is incomplete. Regular season + postseason; preseason excluded. No-TD games stay in the archive.</p>
   <p className="py-1">Selected timing model: {history.clockModel.selected==='uniform'?'pooled historical clocks':'historical clocks by game-total band'}. Held-out game-winner log loss: {history.clockModel.holdout[history.clockModel.selected as 'uniform'|'totalBands'].logLoss.toFixed(3)}; equal-game baseline {history.clockModel.holdout.uniform.logLoss.toFixed(3)} across {history.clockModel.holdout.uniform.slates} slates (lower is better). The total-band candidate scored {history.clockModel.holdout.totalBands.logLoss.toFixed(3)} and failed the release gate; the baseline is retained. Historical player probabilities and ticket returns are not validated.</p>
   {past&&<p className="py-1 font-bold">{past.player}: {past.firstTDs} career game-first TDs in this archive; {past.earlySlateWins} early-slate wins or ties. Descriptive counts, not a forecast or opportunity-adjusted rate.</p>}
   <div className="overflow-auto"><table className="w-full text-[10px]"><thead><tr><th>Season</th><th>Completed / PBP</th><th>First TD</th><th>No TD</th><th>Missing clock</th></tr></thead><tbody>{history.coverage.map(r=><tr key={r.season} className="border-t border-white/10 text-center"><td>{r.season}</td><td>{r.completedGames} / {r.pbpGames}</td><td>{r.firstTDs}</td><td>{r.noTD}</td><td>{r.unknownClock}</td></tr>)}</tbody></table></div>
   <p className="flex flex-wrap gap-3 py-1 font-bold text-gold"><a href="/data/first-sunday-six/first-td-games.csv" download>Every game / scorer CSV</a><a href="/data/first-sunday-six/early-sunday-winners.csv" download>Sunday slate winners CSV</a><a href="https://github.com/nflverse/nflverse-data" target="_blank" rel="noreferrer">Source: nflverse</a></p>
  </details>
  <details className="text-[10px] border-t border-white/10 pt-1"><summary className="cursor-pointer font-bold">How estimates and grades work · limitations</summary><p className="py-1">Game-level First TD market estimates determine scorer shares. Overfull fields are normalized within each game; missing probability stays unassigned. Games compete using empirical first-touchdown clocks from the historical archive. A total-band candidate was selected on 2022–2023 slates and evaluated separately on 2024–2026 completed slates. It failed the held-out release gate, so pooled historical clocks are retained. Player shares still come from current First TD markets; they are not calibrated player predictions. Equal-clock probability is withheld, not assigned an assumed payout. Opening possession, injuries and dependence between scorer identity and scoring time remain limitations. Same-clock tie settlement is unverified. No exact “true probability” is known.</p><p>Cash EV = estimated chance × decimal odds − 1; grades use existing S ≥ +6%, A ≥ +3%, B ≥ +1%, C ≥ −1%, D ≥ −3%, else F. Grades exclude bonuses. First TD inputs expire after 3 hours and all estimates close at the first eligible kickoff. Captured promotion prices do not auto-refresh. Promotion eligibility, token requirements, ties, expiry and caps must be confirmed in Caesars. The supplied $500K/$10 rules are not independently verified; last week’s five-winner result is not used as this week’s forecast. No automatic bet or ledger allocation.</p></details>
 </section>;
}
